# Generated by Django 4.1.1 on 2022-10-20 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='menu_name',
            new_name='menu',
        ),
    ]
