# Generated by Django 4.1.1 on 2022-09-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lasst_name',
            new_name='last_name',
        ),
    ]
