# Generated by Django 4.1.1 on 2022-10-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menurestaurant',
            options={'verbose_name': 'menu', 'verbose_name_plural': 'menus'},
        ),
        migrations.AlterField(
            model_name='menurestaurant',
            name='menu_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
