# Generated by Django 4.1.1 on 2022-10-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_fooditem_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menurestaurant',
            name='menu_name',
            field=models.CharField(max_length=50),
        ),
    ]
