# Generated by Django 4.1.1 on 2022-11-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderedmenu_table_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedmenu',
            name='bracelet',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
