# Generated by Django 4.1.1 on 2022-12-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0005_alter_openinghour_options_and_more'),
        ('orders', '0008_order_bracelet_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='vendor.vendor', verbose_name='Restaurant'),
        ),
    ]
